#!/bin/bash
#
# Description: ENTRYPOINT for running BiStorm Docker Images in Containers

# Use this file for customizing the default behavior when a container is created

# USED TO INITIATE PHP FROM THIS SCRIPT
set -e
echo $BUILD_TYPE

set -- npm run start "$@"

if [ "$BUILD_TYPE" == "production" ]; then
    rm -rf /node_modules
    npm i --save express forever
    set -- npm run start:prod "$@"
fi

exec "$@"
