# This is for building and deploying containers to the Heroku staging pipeline

version: '3'
      
services:
  # Instagram Proxy
  igdata:
    image: instaproxy:latest
    environment:
      - "PORT=80" # Internally used
    container_name: instaproxy
    networks:
     - o3dv_app_stg
    ports: 
     - "3000:443" # Externally used
  # Frontend/UI (Nginx proxy)
  o3dv:
    image: open3dviewer:latest
    environment:
      - "BUILD_VER=${BUILD_VER}"
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        build_type: staging 
        node_env: production
        build_ver: ${BUILD_VER}
        port: 443 # internally used
    environment:
      - "PORT=443" # internally used
    container_name: o3dv
    ports:
     - "8080:443" # externally used
    networks:
     - o3dv_app_stg
     
networks:
  o3dv_app_stg:  
