FROM jonmcquade/alpine-nginx-nodejs

COPY ./package.prod.json /
COPY ./public_build/ /build/ 
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

RUN sed -i "s/PORT/$PORT/g" /etc/nginx/nginx.conf

RUN mv /package.prod.json /package.json && \
    rm -f /build/app.js && \
    npm install --save cross-env compression express express-history-api-fallback && \
    cd /build; ls -l

CMD nginx -g "daemon off;"

 

