FROM node:8.9.4-alpine

COPY ./server.js /
COPY ./public_build/ /build/ 

RUN npm install cross-env path compression express express-history-api-fallback && \
    cd /build; ls -l

CMD node /server.js --bind 0.0.0.0:$PORT

 

