version: '3'
      
services:
  instaproxy:
    image: instaproxy
    build: 
      context: ./social/insta-proxy
      dockerfile:  Dockerfile
      args: 
        build_type: production
    container_name: instaproxy
    ports: 
     - "3000:3000"
    networks:
     - app
  o3dv:
    image: o3dv
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        build_type: production
    container_name: o3dv
    ports:
     - "80:80"
    links:
     - instaproxy
    networks:
     - app
     
networks:
  app:  