version: '3'
      
services:
  # Reverse Proxy provided by traefik  
  traefik:
    container_name: app_proxy_dev
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '443:443'
      - '8081:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app 
  instaproxy:
    container_name: instaproxy_dev
    image: jonmcquade/instaproxy:dev
    labels:
      - 'traefik.backend=proxy'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:igproxy.docker.localhost'
    environment: 
      - NODE_ENV=development
      - PORT=3000
    build: 
      context: ./social/insta-proxy
      dockerfile:  Dockerfile
      args: 
        build_type: development
    ports: 
     - "3000:3000"
    networks:
     - app
  o3dv:
    container_name: o3dv_dev
    image: jonmcquade/open3dviewer:dev
    labels:
      - 'traefik.backend=app'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:o3dv.docker.localhost'
    environment: 
      - NODE_ENV=production
      - PORT=80
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        build_type: development
    volumes:
      - ./src:/src
    ports:
     - "8080:8080"
     - "3001:3001"
     - "3002:3002"
    links:
     - instaproxy
    depends_on:
     - instaproxy
    networks:
     - app
     
networks:
  app:  
