version: '3'
      
services:
  # Reverse Proxy provided by traefik  
  instaproxy:
    image: instaproxy:latest
    build: 
      context: ./social/insta-proxy
      dockerfile:  Dockerfile
      args: 
        build_type: production
        node_env: production
    environment:
      - PORT=80 
    container_name: instaproxy
    ports: 
     - "3000:80"
    networks:
     - app
  o3dv:
    image: open3dviewer:latest
    env_file:
      - prod-build.env
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        build_type: production
        node_env: production
    container_name: o3dv
    ports:
     - "80:80"
    links:
     - instaproxy
    depends_on:
     - instaproxy
    networks:
     - app
     
networks:
  app:  
