version: '3'
      
services:
  instaproxy:
    image: instaproxy:latest
    build: 
      context: ./social/insta-proxy
      dockerfile:  Dockerfile
      args: 
        build_type: production
        node_env: production
    environment:
      - "PORT=3000"
    container_name: instaproxy
    ports: 
     - "3000:3000"
    networks:
     - app
  o3dv:
    image: open3dviewer:latest
    environment:
      - "PORT=80"
      - "BUILD_VER=${BUILD_VER}"
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        build_type: production
        node_env: production
        build_ver: ${BUILD_VER}
    container_name: o3dv
    ports:
     - "80:80"
    links:
     - instaproxy
    depends_on:
     - instaproxy
    networks:
     - app
     
networks:
  app:  
