FROM node:8.9.4-alpine

COPY ./server.js /
COPY ./package.prod.json /
COPY ./public_build/ /build/ 

RUN mv /package.prod.json /package.json && \
    npm install --save cross-env compression serve express express-history-api-fallback && \
    cd /build; ls -l

CMD node /server.js --bind 0.0.0.0:$PORT

 

