#!/bin/bash
#
# Description: ENTRYPOINT for running Docker Images in Containers

# Use this file for customizing the default behavior when a container is created

set -e
export BUILD_TIME=$BUILD_TIME
export BUILD_TYPE=$BUILD_TYPE
export BUILD_VER=$BUILD_VER

echo "BUILD_TIME: $BUILD_TIME"
echo "BUILD_TYPE: $BUILD_TYPE"
echo "BUILD_VER: $BUILD_VER"

sed -i "s/listen 80/listen ${PORT}/g" /etc/nginx/nginx.conf && \

if [ "$BUILD_TYPE" == "development" ]; then
    set -- npm run start "$@"
    exec "$@"
else    
    set -- nginx -g "daemon off;" "$@"
    exec "$@"
fi
