#!/bin/bash
#
# Description: ENTRYPOINT for running BiStorm Docker Images in Containers

# Use this file for customizing the default behavior when a container is created

# USED TO INITIATE PHP FROM THIS SCRIPT
set -e
echo $BUILD_TYPE

if [ "$BUILD_TYPE" == "development" ]; then    
    set -- npm run start "$@"
else    
    cd / && npm install express path cross-env && \
    set -- PORT=$PORT node server.js "$@"
fi

exec "$@"
